src/iframe/js/library/autoQuery.js
src/iframe/json/menumetadata.json

Made it so you can correct for skewing in a dataset during color-coding.
Here is the basic idea: https://www.desmos.com/calculator/px5vxgzujw
In that example, s = how skewed the value you are color coding on is.
Green = correction for right skewness.
Purple = correction for left skewness.
Red = how it is if you don't set skew for a dataset or skew is set to 0

Added Skew Correcting on Color Coding

---

src/iframe/js/library/autoQuery.js
src/iframe/js/library/geometryLoader.js

Made it so different county/tract features don't get rejected by `renderGeoJson` by setting the id to a combination of the data, and the county/tract id.
closes #159

Administrative Tracts may now overlap

---

src/iframe/js/library/charting/scatterplotManager.js

Remember when I said I didn't think getValues() being async would cause any problems?

Fix "xfeat is undefined" bug in scatterplots

---

src/iframe/js/library/charting/chartSystem.js
src/iframe/js/library/charting/scatterplotManager.js
src/iframe/js/library/mapDataFilter.js
src/iframe/js/library/mapDataFilterWorker.js
src/iframe/js/library/mapDataFilterWrapper.js
src/iframe/js/library/valueIngester.js
src/iframe/map2.html

At low zoom levels, the filter now samples data instead of passing ALL of it to the charts. The amount of sampling coarsely increases as the map is zoomed out.
For reference, if you zoom to see about a third of the contiguous US, you would normally get about ~1,000-1,500 counties appear in the graph if there was no sampling. In this branch, the amount should be greatly reduced.
Later there probably should be some UI element alerting the user that sampling is taking place, or else the results may be unexpected.

Filter sampling

---

src/iframe/js/library/charting/Feature.js
src/iframe/js/library/charting/chartBtnControls.js
src/iframe/js/library/charting/chartSystem.js
src/iframe/js/library/charting/feature.js
src/iframe/js/library/charting/scatterplotManager.js
src/iframe/js/library/charting/singleChartManager.js
src/iframe/js/library/mapDataFilter.js
src/iframe/json/graphPriority.json
src/iframe/map2.html

Lots of internal changes that amount to the following things:
- Charts can now tell the difference between identically named constraints, i.e. things like SVI county and SVI tract are now separately plottable and will not be confused with one another.
- Human-readable names are now much easier to get (Closes #212).
- Scatterplots are now actually meaningful (guess what? Data coming into the scatterplots previously wasn't being joined on _anything_, meaning the distribution of data was effectively random. They are now properly joined by GISJOIN. Having to admit that I designed the world's most useless scatterplot was hard.)
Charting _may_ be noticeably slower with these changes, especially scatterplots.

Qualified feature names

---

src/css/charts.css
src/js/library/charting/chartFrame.js
src/js/library/charting/chartSystem.js
src/js/library/charting/singleChartManager.js
src/js/library/resizable.js

Makes charting suck a little bit less.
* The resizable handle should now show up properly (isn't cut off) and should sit in the same place in the top right corner no matter where the window is scrolled to (Closes #216 - doesn't put the handle in all 4 corners, but I think it solves the spirit of the problem, that being resizing was way to cumbersome and annoying)
* The charting window should no longer appear underneath the menu when first activated (Closes #217)
* There is no more useless horizontal scrollbar (Closes #226)
* Charts now have a maximum size, allowing multiple to show up if given adequate space (Closes #214)
* Other small improvements to look and feel

More chart QOL

---

src/js/library/charting/histogram.js
src/js/library/charting/kernelDensityEstimator.js

Datasets with large individual entries, notably median household income, should no longer cause KDE in histograms to stop working.
Closes #252 .

Fix large numeric datasets breaking KDE

---

src/js/library/autoQuery.js
src/js/ui/DefensiveOptimization.js

Fixed a bug where if you were zoomed out far enough, for a defensive optimization warning to come up, and then unchecked the layer causing it, the warning would persist. This involved making the flag which sets which blockers are on into integers, because the user may select multiple layers.

Remove Blocker Warning if Layer Unchecked

---

src/js/library/charting/chart.js
src/js/library/charting/chartSystem.js
src/js/library/charting/controlDropdown.js
src/js/library/charting/histogram.js
src/js/library/charting/lineGraph.js
src/js/library/charting/scatterplot.js
src/js/library/resizable.js
src/js/static/darkMode.js

All charts should now respect dark mode (#308). In doing this, I also had to fix #307, so you get it for free.
Also, lag on the client should be reduced, especially in COVID charts, since queries no longer happen every 2 seconds. Now that timer runs every 1.5 seconds and only does re-rendering of chart frames, nothing more.

Dark mode charts + resizing fixes

---

src/js/ui/NewCharting/ChartTemplates/HistogramChart.js
src/js/ui/NewCharting/ChartingResizable.js
src/js/ui/NewCharting/KDEWrapper.js
src/js/ui/NewCharting/makeFrame.js

This re-introduces KDE to histograms in a React-friendly way.
Known issue: the Input up/down buttons don't work on Firefox. No idea why - I think it honestly might be a bug in MaterialUI.

Add KDE to ported histogram

---

src/css/charts.css
src/js/ui/NewCharting/ChartTemplates/LineGraph.js
src/js/ui/NewCharting/ChartingResizable.js
src/js/ui/NewCharting/ChartingWindow.js
src/js/ui/NewCharting/makeFrame.js

Returns the old functionality where you could hover over lines in the COVID chart to see what county there were a part of.
The Rnd component made this an _absolutely colossal_ pain, for more reasons than one. Please test thoroughly, as this fix definitely involves some really hacky duct-tape solutions.
Closes #361.

Reimplement covid line tooltips

---

src/js/ui/NewCharting/ChartingWindow.js
src/js/ui/NewCharting/makeFrame.js

This _should_ address county hovering and highlighting not working - only tested on FF, so make sure it works on your browser first.

Fix unresponsive hovering on covid graph

---

src/js/ui/NewCharting/ChartTemplates/BoxPlotChart.js
src/js/ui/NewCharting/FrameControls.js
src/js/ui/NewCharting/KDEWrapper.js

Previously, the default name for a dropdown in Charting was "Constraint". It needs to be "Dataset" because we are charting datasets not constraints.
This PR also fixes a 'var' to a 'let' in Boxplot.js

"Constraint" -> "Dataset"

---

src/js/library/Query.js

There was a bug where some certain queries wouldn't end. This PR fixes that.
If the query popup ends when using this workspace as a seed, it should be fixed: workspace=N4IgNghgngpgTgZxALgNqgMYHsxhhgFwEssA7FEAuCQgfQFsYATIiU2gCywFcEYuwTWkVLZGIADQgyKKtxhSYADwAObJswDKBCARgoAZhDB8p2UgioQRBbbv1oQAJgAMARhcNmrdl178cIRExfQBdMzJLahskNFCAXwlMHDxCEnJkEBVuACMwIgxaBAwuHCQpGWQ5BRBlNVINJjs9Q2NTEHMo61JbHRbHFTgsFXhiGAQAOgBRADkAJQB5ABklgFlZgBVJLKGRuDHJgDEN2g2pgEEAYQAJKbntweHRonGJpamANSml2hBwjsiVhiKFQCX+NngfEIrRMNVIEHEmU0HAgcGYAAIAOpYOAAawQagw+ikOR4DViIAAtB4AKwTABsbgA7C56TSACxOACc9IAHEyaW4JOyXBMnPSAMy8ly8mlc3lclwSmn0+kSakudkTCWatxcrlONz8mkudzC0UCpzsmnG+U0nU0kDxIA

Fix Loading Popup Bug

---

src/js/ui/NewCharting/ChartTemplates/LineGraph.js

Adds labels to the axes and removes the query notice (the "getting data..." text).

Small polish to COVID chart

---

src/js/library/autoQuery.js

Basically, a fix I made earlier made it so the query class could return immediately. The query id set was not populated yet once it returned, causing many issues. This populates the id set before the call is made.

Fix Bug Relating to Zooming and Changing Slider

---

src/js/static/menuOverwrite.js

Lets users select dates up to yesterday for the gridMET dataset, since we will very soon be updating it regularly.

gridMET time range goes up to yesterday

---

src/json/menumetadata.json

This adds 6 of the 8 AQI Contaminants. They can be found by searching 'EPA' in the Aperture search bar. Shrideep wants to get these in this morning, if possible, for a PI meeting this afternoon.
Known issue: when a contaminant is added the icon does not automatically color-code - this must be selected in the inspection pane. Shrideep saw this and said it is fine for the time being. 
I will add the last 2 contaminants once they're done being ingested, hopefully by the end of the weekend.
Just check that you can see these 6 datasets, that they turn on, and it doesn't break anything.

Ingest aqi datasets

---

src/js/library/Color.js
src/json/menumetadata.json

Colors/graphing for the general aqi score. The dataset in aperture is called `EPA AQI Score`.
Some thoughts on this
- Aperture by default uses a date range for this dataset. This is wonderful in the inspection pane when you want to look at the graph of aqi over time for a given county
- The colors on the map only relate to the _first_ date in the date range. To me, this is less than intuitive.
I do think this is ready to merge, unless anyone finds a bug/other issue. I'd love to hear other opinions on the map coloring. Because this dataset does have both a range and a single-date visual component, I'm not sure about the best way to address this.

Metadata for general aqi

---

src/js/ui/NewDataExploration/WorkspaceControl/WorkspaceSearchbar.js

Shrideep asked me to make this change to Aperture. It just removes the total_datasets field from the dataset explorer when the search bar is inactive. This is a 1-line change.

Update total datasets display

---

src/js/library/Query.js
src/js/static/menuOverwrite.js

Makes MACA future climate predictions available as `Future Climate (Tract/County)`.
This is just 1 of 40 models that will eventually be ingested and there are some issues with the underlying dataset (two variables are missing and had to be left out of Aperture), so I will need to update this eventually, but everything that's _here_ should work fine.
Test all the variables of the new dataset, make sure coloring works, make sure it shows up across the entire country, and let me know if anything looks weird. (Remember that the tract version of the dataset is missing some tracts because the spatial resolution of the data isn't high enough)

Make preliminary MACA data available
