src/Iframe/Dependencies/selectGenerator.js
Missed a line when re-wrote the checklist code.
=> Fixed Unchecking

src/Iframe/Dependencies/MapJS/map2.js, src/Iframe/Dependencies/selectGenerator.js, test/Iframe/Dependencies/selectGenerator.js
I missed a few lines of inline JS in my JS code.
=> Removed More Inline JS

src/Iframe/Dependencies/getInfrastructure.js
This is so Thomas can use this function within his code.
=> Documented and added optional callback parameter to queryGRPC()

src/iframe/js/frame-specific/map2.js, src/iframe/js/grpc/GRPC_Querier/grpc_querier.bundle.js
Fixing some issues with running the GRPC querier on the Sustain site.
=> Compound queries

src/iframe/css/third-party/leaflet-sidebar.css, src/iframe/js/frame-specific/map2.js, src/iframe/js/library/renderInfrastructure.js
Just a couple of small quality of life fixes, not all of them need to be changed though, and there are still some more things I would like to change.
So far I have altered the css for the menu so that the sliders don't go on top the the header, as well as alter the width and added some js to close the menu when the map is clicked on, but since queries are made every time the menu is closed this many not be wanted
=> Small tweaks

src/iframe/css/IframeStyle.css, src/iframe/css/third-party/leaflet-sidebar.css, src/iframe/js/frame-specific/map2.js, src/iframe/js/library/autoMenu.js, src/iframe/js/library/chartSystem.js, src/iframe/js/library/exampleFilterDigester.js, src/iframe/js/library/resizable.js, src/iframe/js/library/translation.js, src/iframe/js/ui/menuGenerator.js, src/iframe/map2.html
Fix a problem that caused Matt's UI to disappear from dev... for real this time.
=> Seriously actually restore Matt's ui

src/iframe/js/frame-specific/map2.js, src/iframe/map2.html
Added topo and sattelite layers.
=> Added Layer Controls

src/iframe/js/library/autoMenu.js, src/iframe/js/library/autoQuery.js, src/iframe/json/menumetadata.json
Added FEMA risk index. The colors are a bit wonky because the skewing of the dataset is bad.
=> Added Fema Risk

src/iframe/js/library/autoQuery.js, src/iframe/js/library/geometryLoader.js, src/iframe/js/library/queryWorker.js, src/iframe/js/library/smartQuerier.js
Resolves a bug where county GISJOIN information was not being properly queried (i.e. not properly implementing hacky workaround to deal with mongodb nonsense).
=> Fix county querying

src/iframe/js/library/autoQuery.js, src/iframe/js/library/renderInfrastructure.js, src/iframe/json/menumetadata.json
Added the ability to "map" a colorway. Look at menumetadata.json to see what I did.
=> Fema colorway

src/iframe/js/frame-specific/map2.js, src/iframe/js/library/smartQuerier.js
Daniel deleted this code so I added it back in
=> Functioning Graph Button

src/iframe/js/frame-specific/map2.js, src/iframe/js/grpc/GRPC_Querier/grpc_querier.bundle.js, src/iframe/js/grpc/GRPC_Querier/grpc_querier.js, src/iframe/js/library/autoMenu.js, src/iframe/js/library/autoQuery.js, src/iframe/js/library/geometryLoaderWorker.js, src/iframe/js/library/queryWorker.js, src/iframe/js/ui/preloading-menu/components/PreloadingMenu.js
Added a `DEV` log which will tell you which machine you are connected to. I had to pass the number to the workers on config.
=> Random Lattice Num

src/iframe/js/library/autoQuery.js, src/iframe/js/library/charting/chartSystem.js, src/iframe/js/library/mapDataFilter.js, src/iframe/js/library/mapDataFilterWorker.js, src/iframe/js/library/mapDataFilterWrapper.js, src/iframe/js/library/renderInfrastructure.js, src/iframe/js/library/resizable.js
When a user unchecks a collection, that data is now removed from the filter, making it unplottable and hopefully freeing up some heap space.
=> Filter collection clearing

src/iframe/js/ui/modeling/components/ModelMenu.js
=> Make Other Clustering Work

src/iframe/json/menumetadata.json
Just added a dataset, its actually pretty cool, thanks @menuka94
=> Proximity Queries

src/iframe/js/ui/menuGenerator.js
Added the `resetConstraintsForLayer` function to `menuGenerator.js`. Just provide it the `layerName` and it will reset all the constraints for that layer.
=> Reset Constraints Utility Function

src/iframe/js/library/autoQuery.js, src/iframe/json/graphPriority.json
The tract proximity dataset is now plottable with both histograms and scatterplots.
=> Chart tract proximity

src/iframe/js/library/charting/scatterplotManager.js
=> Fix scatterplot not disappearing when it doesn't have enough features

src/js/library/boundsToGISJOIN.js
This is necessary for it to work on the site.
=> Fix File Path

index.js, package.json, src/css/dataExploration.css, src/css/main.css, src/js/library/autoMenu.js, src/js/ui/menuGenerator.js, src/json/menumetadata.json
I also folded in a change to make the defensive stuff come up on the right, because it could be obscured by the menu on the left.
=> Categorical sliders

src/js/library/autoMenu.js, src/js/library/autoQuery.js, src/js/ui/menuGenerator.js, src/json/menumetadata.json
Now, if a range constraint has `plus=true`, and it's upper bound is selected, the UI will add a `+` after the final value, and `2147483647` will be the upper bound in the query.
=> Added Unlimited Upper Bound Option to Constraints

src/css/dataExploration.css
layerConstraints and contentSection classes have their max-heights significantly increased.
=> Increase max-height

src/js/library/autoMenu.js, src/js/library/autoQuery.js, src/js/ui/DefensiveOptimization.js, src/json/menumetadata.json
Set blocker levels of all features to that of what the county was, with the option to override. I overrode the Flood Zones to be very zoomed in.
=> Add Blocker Levels to All Features

package-lock.json
Just so I can merge it into master no problems.
=> Update package-lock.json in dev

src/js/library/autoQuery.js, src/js/library/renderInfrastructure.js, src/json/menumetadata.json
Please test this a lot, there is probably something wrong with it.
=> Intersections on Tracts and Counties

src/js/library/charting/chart.js, src/js/library/charting/chartBtnControls.js, src/js/library/charting/chartFrame.js, src/js/library/charting/chartManager.js, src/js/library/charting/chartSystem.js, src/js/library/charting/controlDropdown.js, src/js/library/charting/covidDataSource.js, src/js/library/charting/dataSource.js, src/js/library/charting/featureDropdown.js, src/js/library/charting/histogram.js, src/js/library/charting/kernelDensityEstimator.js, src/js/library/charting/lineChartManager.js, src/js/library/charting/lineGraph.js, src/js/library/charting/mapDataSource.js, src/js/library/charting/scatterplot.js, src/js/library/charting/scatterplotManager.js, src/js/library/charting/singleChartManager.js, src/js/library/resizable.js
The next step in my Sisiphyian journey to make charting not suck. Lots of small fixes.
* KDE curves now actually work, for real this time (Closes #285)
* The charting window should no longer resize components independently from the window itself (Closes #286)
* Graphs are more responsive: (Closes #289)
* appear more quickly after being created
* valid features are now filled from the map instantly
* clicking on any axis button instantly refreshes the graph
* changing the COVID feature now updates the chart instantly
* Changed bad sizing defaults: (Closes #288)
* charting window's initial size is no longer smaller than the minimum size (lol), fixing a problem where horizontal resizing didn't work
* all charts now have a minimum height, preventing them from displaying as useless degenerate …
=> Chart robustness and QOL

src/css/charts.css, src/js/library/resizable.js
=> Charting window resizable from all four corners

.github/workflows/nodejs.yml
Hopefully this will stop node.js from dying during tests.
=> Increase node.js version in CI

src/js/ui/modeling/components/ModelMenu.js, src/json/menumetadata.json
=> A few things from the Trello list

src/js/ui/menuGenerator.js
=> Gray Sliders

index.html, index.js, package-lock.json, package.json, src/css/main.css, src/js/static/navButtons.js, src/js/ui/ConditionalWidgetRendering.js, src/js/ui/GoTo.js, src/js/ui/Root.js, src/js/ui/global/GlobalState.js, src/js/ui/global/GlobalTheme.js, src/js/ui/widgets/ClusterLegend.js, src/js/ui/widgets/DefensiveOptimization.js, src/js/ui/widgets/GoTo.js, src/js/ui/widgets/PreloadingMenu.js
Centralized mostly all of the existing react components into one component. Added global state and conditional rendering for a few of the widgets. @honeybadgerofdoom We will go over this during our meeting tomorrow, so wait to review.
=> Root React Component

src/js/library/Query.js, src/js/library/autoQuery.js, src/js/library/queryWorker.js, src/js/library/smartQuerier.js
Purged some code we didnt need anymore, added `kill` method to `Query`.
=> Query Optimizations

src/js/library/autoMenu.js, src/js/ui/NewDataExploration/AdvancedConstraints.js, src/js/ui/NewDataExploration/ConstraintSlider.js, src/js/ui/NewDataExploration/LayerControls.js, src/json/menumetadata.json
- Added option for `source` which links to whatever the source page is for the layer/collection
- Added descriptions for all neon stuff
- Added units to the slider
- Made slider text bold. We should make all of the constraints bold, but I didn't want to run into any merge conflicts with @honeybadgerofdoom 's date branch.
=> Source Option and Neon Info

package-lock.json, package.json, src/js/library/Query.js, src/js/library/autoQuery.js, src/js/library/renderInfrastructure.js, src/js/ui/widgets/Popup.js, src/js/ui/widgets/PopupTimeChart.js
Added temporal charts to popups. I used nivo because it seems like our version of the chart popup was more focused around covid and I wanted to get this prototyped quickly. Once ours matches nivo's capabilities we can switch over.
Some of the code is a bit wonky, cause this implementation should just be temporary.
=> Temporal Charts on Popup

src/js/library/autoQuery.js, src/js/library/renderInfrastructure.js, src/js/ui/widgets/Popup.js, src/js/ui/widgets/PopupTable.js, src/js/ui/widgets/PopupUtils.js, src/json/defaultImportantFields.json
Fixed all the bugs I have found and refactored a bit.
@Marc-9 I didn't make the 'x' easier to access yet, because I'd like to let @honeybadgerofdoom finalize the styling of this before I put too much styling.
=> Popup Bug Fixes and Refactor

src/js/ui/NewModeling/NewModeling.js
@honeybadgerofdoom I added a comment in the code where you'll wanna set state. The `catalog` variable will have everything you need. The `mappedCatalog` will have it in a slightly more hierarchical format if you want to use that instead.
=> Create Getter for Modeling Catalog

src/js/ui/widgets/Popup/PopupTable.js, src/js/ui/widgets/Popup/PopupTableEntry.js, src/js/ui/widgets/Popup/PopupTableValue.js
Created an `entryProperties` prop for `PopupTableEntry.js`, which also gets passed to `PopupTableValue.js`. It is an object with some pretty self explanatory key/values. Right now there is: 
```
isCurrentColorField: Is this the current colorfield?
canBeColorField: can this be a colorfield?
isTemporal: is this a temporal field?
```
=> Matt table object

src/js/ui/NewCharting/ChartTemplates/HistogramChart.js
Should address the issue of histograms sometimes having black bars. Only tested on FF, etc. etc.
=> Fix newly created histogram bars being black

package-lock.json, package.json, src/js/ui/NewDataExploration/Layer.js, src/js/ui/NewDataExploration/Workspace.js, src/js/ui/NewDataExploration/WorkspaceControls.js
- Current state of intersections is saved
- State of each layer being "expanded" is saved
- State is converted & compressed to base64, which should make it cleaner & smaller to share
Make sure to save a new state before you load one of the old ones from the previous branch since this one decompresses it.
=> Better Save and Load

package-lock.json, src/js/ui/NewDataExploration/Workspace.js, src/js/ui/NewDataExploration/WorkspaceSearchbar.js
Allows the workspace to be seeded by the URL.
To test, you can add this string to your URL in the browser and reload:
`?workspace=N4IgNghgngpgTgZxALgNqgMYHsxhhgFwEssA7FEAuCQgfQFsYATIiU2gCywFcEYuwTWkVLZGIADQgyKKtxhSYADwAObJswDKBCARgoAZhDB8p2UgioQRBbbv1oQAJgAMARhcNmrdl178cIRExfQBdMzJLahskNFCAXwlMHDxCEnJkEGxuUgIoLxY2Th4+ASDRLHEpGWQ5BRBlNVINJjs9WTh5CIsrGzaHVGd3T0ZC3xKAwWEK8XCsyN7c2PQQUghxTNcPAp9i-zLpkMkQS3sUVCcAFgBOa4kAVgA2W+uEhKT53HxiGpOANyItGyuXyAHEAJKaABSAHlwQA5Y41OqKVTqLQ6drIIwmermKLWXL9c4gABKAAUADK0AAqAAkAKIAWQZmhAc3xiwIy3eyS+aV+CABtCsdAh0LhiOqGRRDTRzQxZ1qnTxC2iRMxAzJVNpjJZbI5asJ3POoDWG211PpzNZx1OWNQLgkLgAdABme5veJzGzwPiEDryeJAA`
This should seed your menu with this (it may take awhile to load because it has to wait for all the options in the menu to be loaded before it loads in): …
=> Workspace from URL

src/js/library/autoMenu.js, src/js/ui/NewDataExploration/Layer.js, src/js/ui/NewDataExploration/LayerControls.js, src/js/ui/NewDataExploration/WorkspaceControls.js, src/js/ui/NewDataExploration/WorkspaceLayers.js, src/js/ui/NewDataExploration/WorkspaceSearchbar.js
Fixes some gripes I had with the performance of the workspace.
- Memoized some things so adding a lot of layers isn't progressively slower as you add more
- Only gets whats "needed" from the server on startup, meaning we don't have to wait as long for the menu to load.
=> Fix workspace performance

package-lock.json, src/js/ui/NewDataExploration/CustomAlert.js, src/js/ui/NewDataExploration/Load.js, src/js/ui/NewDataExploration/Save.js, src/js/ui/NewDataExploration/SaveAndLoadAndShare.js, src/js/ui/NewDataExploration/SavedWorkspaceSlotSelection.js, src/js/ui/NewDataExploration/Share.js
This PR styles the save/load/share components. Open to suggestions as always.
=> Style Save/Load/Share

src/css/main.css, src/js/library/autoQuery.js, src/js/library/renderInfrastructure.js, src/js/ui/NewDataExploration/ConstraintSlider.js, src/js/ui/NewDataExploration/IndividualConstraint.js, src/js/ui/NewDataExploration/Save.js, src/js/ui/NewDataExploration/SaveAndLoadAndShare.js, src/js/ui/NewDataExploration/SavedWorkspaceSlotSelection.js, src/js/ui/TabSystem.js, src/js/ui/widgets/DefensiveOptimization.js, src/js/ui/widgets/Popup/PopupUtils.js
- Fix table values that made no sense like epoch time not showing up as a date.
- Limit floats in the table to 3 decimal places
- Temporarily disable modeling tab
- Range constraints go grey when they don't actually affect the query
- Risk index constraints now have sliders again
- A thing tells you if a query is happening
- Fix the little bugs in save & load, limiting single word length
- Menu title on popup makes more sense now
- Units show up again on popup
Sadly wasn't able to fix the intersection color bug yet, but luckily no one should notice as it doesn't affect interactability.
=> General Polishing and Improvements

src/js/ui/NewDataExploration/LayerControls.js
=> Remove 'graph me' and 'reset constraints' from layer controls (for now)

src/js/library/Query.js
The request is is in a try-catch loop so it shouldn't break anything.
=> Add Safe Query Logging

src/js/ui/NewDataExploration/CustomAlert.js, src/js/ui/NewDataExploration/Load.js, src/js/ui/NewDataExploration/Save.js, src/js/ui/NewDataExploration/SavedWorkspaceSlotSelection.js, src/js/ui/NewDataExploration/Share.js
This PR adds an alert asking users to confirm before they overwrite an existing workspace
=> Confirm overwrite workspace

src/js/library/Query.js, src/js/library/autoQuery.js
Logging to the query API is now a standalone function and Druid queries do it too. @Marc-9 Make sure the payload object looks okay, I changed it a little bit.
=> Log Druid queries

src/js/ui/NewDataExploration/Layer.js, src/js/ui/NewDataExploration/WorkspaceLayers.js
This fixes 2 files where I had (stoooopidly) pushed DOM elements into an array and rendered that instead of using .map(). I wrote these when I was still getting the hang of things. Don't judge me.
Probably some more aperture refactoring to come - there are a few more little things I want to clean up in the code base.
=> Fix a couple sloppy iterative renders

package-lock.json, src/js/ui/NewDataExploration/WorkspaceSearchbar.js
This PR fixes some issues I had with the old search bar.
- I've been wanting to change this around for a while. The issue is that previously, when you searched for a dataset and selected it, the search would automatically reset. Thus, if you wanted to add all County datasets, you would have to type 'county' over and over again, clicking one at a time. This PR not only fixes that, but adds an 'add all' button when filtering, so you can add all of your search results to the workspace at once.
- Put the results of the search in a table, which I think looks a bit nicer.
- To test this, just play around with searching, adding, and removing datasets to/from the workspace.
=> New dataset searchbar

src/json/menumetadata.json
Added soils data, it may be very slow to query for the next day or so because I still need to set up the indexing on it.
=> Added Soils Data

src/json/menumetadata.json
This PR adds the last two AQI contaminants to Aperture. They are Sulfur Dioxide and Carbon Monoxide. Test by adding these to the workspace and checking that they show up on the map, etc...
=> Adds Sulfur Dioxide and Carbon Monoxide
